version: '3'
services:
  mysql-host:
    build:
      context: ./mysql
    restart_policy:
      condition: on-failure
      max_attempts: 3
    volumes: 
      - ../db:/var/lib/mysql
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
  magento-host:
    build:
      context: ./magento
    restart_policy:
      condition: on-failure
      max_attempts: 3
    volumes: 
      - ../webroot:/var/www/html
      - ./magento/local.xml:/var/www/html/app/etc/local.xml
    ports:
      - '80:80'
      - '9000:9000'
    command: wait-for-it.sh mysql-host:3306 -- init.sh -c "http://magento.dev/"