version: '3'
services:
  mysql-host:
    build:
      context: ./mysql
    volumes: 
      - ../db:/var/lib/mysql
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
  magento-host:
    build:
      context: ./magento
    environment: 
      DOMAIN: magento.dev
      DOCKER_HOST_IP: $DOCKER_HOST_IP
    volumes: 
      - ../webroot:/var/www/html
      - ./magento/init.sh:/usr/local/bin/init.sh
      - ./magento/local.xml:/var/www/html/app/etc/local.xml
    ports:
      - '80:80'
    command: wait-for-it.sh -t 45 mysql-host:3306 -- /bin/bash init.sh