version: '2'
services:
  mysql-host:
    build:
      context: ./mysql
    restart: always
    volumes: 
      - ../db:/var/lib/mysql
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
  magento-host:
    build:
      context: ./magento
    restart: always
    volumes: 
      - ../webroot:/var/www/html
      - ./magento/local.xml:/var/www/html/app/etc/local.xml
    ports:
      - '80:80'
      - '9000:9000'
    entrypoint: init.sh -c "http://magento.dev/"